### ISSUE TITLE
panel / labels?

### ISSUE THREAD

**Issue by KeLaiFu** [covertneko/vcf-20#1]
I'm curious about this version of the filter, I've never seen one with quite so many inputs / outputs!

there doesn't seem to be any kind of labelling on the PCB though, do you have a picture of the panel with the labels? I could make my own PCB panel once I know what's what.

Thanks

**Comment by covertneko** [comment]
Hey, sorry for the late response, I've been busy with school. I've updated the repo with the latest version, I forgot to upload it when I finished it last year. It includes gerbers for a PCB panel as well as the original design file (panel.afdesign). I use the kicad HTML BOM plugin to make populating the PCB easier, so the silkscreen isn't super informative.

I never really expected anyone to be interested in this since it's a bit of a mess, and I haven't included any instructions on calibrating the 3 trimmers on the back which is necessary to have working crossfade, resonance, and notch. You're welcome to give it a shot but it's not a very friendly build process, so ymmv. I'm happy to answer questions but I can't promise a fast response.

The high pass and low pass work well and the resonance can sound really nasty and overpowering in a potentially good way with the drive turned up, but I wouldn't suggest this as a general purpose filter without some major improvements by someone smarter than me haha.

I'm closing this issue since I've added the panel files, but feel free to open others if you have more questions and don't mind the delay.
